spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/devdb
    username: devdb
    password: dev123
    driver-class-name : com.mysql.cj.jdbc.Driver
  jpa:
    show_sql: true
    hibernate:
      ddl_auto: create-drop

---
environment: test
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: test
    password: test123
    driver-class-name : org.h2.Driver
  jpa:
    database: h2
  h2:
    console:
      enabled: true
