environment: default
spring:
  config:
    activate:
      on-profile: default
name: prod-YAML
server:
  port: 8080
---
environment: production
spring:
  config:
    activate:
      on-profile: prod
name: prod-YAML
server:
  port: 5000
welcomeMsg : Hello from Prod
---
environment: testing
spring:
  config:
    activate:
      on-profile: test
name: test-YAML
server:
  port: 4000
welcomeMsg : Hello from Test