spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/devdb
    username: devdb
    password: dev123
    driver-class-name : com.mysql.cj.jdbc.Driver
  jpa:
    show_sql: true
    hibernate:
      ddl_auto: create-drop

